### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by donmc123** [QIanGua/Alfred-Workflow-for-Arc#4]
See attached video

https://github.com/QIanGua/Alfred-Workflow-for-Arc/assets/1004792/699cbf63-ff2b-4c67-9d1c-35eb6948e5ee

**Comment by QIanGua** [comment]
Hello @donmc123, can you show the debug info after you run the `Arc Tabs` commands? Have you open the Arc browser?
![CleanShot 2023-06-03 at 20 33 15@2x](https://github.com/QIanGua/Alfred-Workflow-for-Arc/assets/7362290/0ff6c9ed-ec27-4c07-871e-f69fd0f105d3)

**Comment by paularmstrong** [comment]
This happens to me…

> ./list-tabs.js: execution error: Error: TypeError: undefined is not an object (evaluating 'tabsTitle[w][s].length') (-2700)

**Comment by paularmstrong** [comment]
Spaces also has errors:

```
[10:55:34.281] Arc Tabs and Spaces[Script Filter] Queuing argument '(null)'
[10:55:34.537] Arc Tabs and Spaces[Script Filter] Script with argv '(null)' finished
[10:55:34.542] ERROR: Arc Tabs and Spaces[Script Filter] Code 1: windownCount:  3
windowIndex[0]: 1
windowIndex[0] name: Doesn't work · Issue #4 · QIanGua/Alfred-Workflow-for-Arc
spaceCount:  9
spacesTitle:  Browsing,Home,Work,Browsing,Home,Work,Browsing,Home,Work
spacesId:  4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81,4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81,4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81
./list-spaces.js: execution error: Error: Error: Invalid index. (-1719)
```

**Comment by QIanGua** [comment]
> Spaces also has errors:空格也有错误：
> 
> ```
> [10:55:34.281] Arc Tabs and Spaces[Script Filter] Queuing argument '(null)'
> [10:55:34.537] Arc Tabs and Spaces[Script Filter] Script with argv '(null)' finished
> [10:55:34.542] ERROR: Arc Tabs and Spaces[Script Filter] Code 1: windownCount:  3
> windowIndex[0]: 1
> windowIndex[0] name: Doesn't work · Issue #4 · QIanGua/Alfred-Workflow-for-Arc
> spaceCount:  9
> spacesTitle:  Browsing,Home,Work,Browsing,Home,Work,Browsing,Home,Work
> spacesId:  4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81,4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81,4924DD7A-49A6-4E78-93DC-18E77BBFD687,FE534B8A-0E09-448D-BCBB-53E6F44F6444,A146AFF1-DFA1-467C-9C25-B356EF272E81
> ./list-spaces.js: execution error: Error: Error: Invalid index. (-1719)
> ```

Hi @paularmstrong  Thanks for you issue. It seems you open three Arc Windows. My original code doesn't consider multi window case. Maybe It needs to extend the boundary case of code. Any PR are welcome.

**Comment by yimingli** [comment]
> My original code doesn't consider multi window case. Maybe It needs to extend the boundary case of code.

Closing extra arc windows solved the issue for me. Can we add this warning to readme? I tried the workflow a few times before and gave up, until I saw this repo issue.

**Comment by QIanGua** [comment]
> 

Of course, I will add this warning to README.
